[33mWARNING[0m:  [09-04-2024 00:41:14] Python-dotenv could not parse statement starting at line 9
[33mWARNING[0m:  [09-04-2024 00:41:14] Python-dotenv could not parse statement starting at line 12
[33mWARNING[0m:  [09-04-2024 00:41:14] Python-dotenv could not parse statement starting at line 15
[33mWARNING[0m:  [09-04-2024 00:41:14] Python-dotenv could not parse statement starting at line 16
[33mWARNING[0m:  [09-04-2024 00:41:14] Python-dotenv could not parse statement starting at line 18
[33mWARNING[0m:  [09-04-2024 00:41:14] Python-dotenv could not parse statement starting at line 19
[33mWARNING[0m:  [09-04-2024 00:41:14] Python-dotenv could not parse statement starting at line 21
[33mWARNING[0m:  [09-04-2024 00:41:14] Python-dotenv could not parse statement starting at line 22
[32mINFO[0m:     [09-04-2024 00:41:14] Set chroma_server_nofile to 65535
[32mINFO[0m:     [09-04-2024 00:41:14] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [09-04-2024 00:41:14] Starting component System
[36mDEBUG[0m:    [09-04-2024 00:41:14] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [09-04-2024 00:41:14] Starting component SimpleAssignmentPolicy
[36mDEBUG[0m:    [09-04-2024 00:41:14] Starting component SqliteDB
[36mDEBUG[0m:    [09-04-2024 00:41:14] Starting component QuotaEnforcer
[36mDEBUG[0m:    [09-04-2024 00:41:14] Starting component Posthog
[36mDEBUG[0m:    [09-04-2024 00:41:14] Starting component LocalSegmentManager
[36mDEBUG[0m:    [09-04-2024 00:41:14] Starting component SegmentAPI
[32mINFO[0m:     [09-04-2024 00:41:14] Started server process [[36m92510[0m]
[32mINFO[0m:     [09-04-2024 00:41:14] Waiting for application startup.
[32mINFO[0m:     [09-04-2024 00:41:14] Application startup complete.
[32mINFO[0m:     [09-04-2024 00:41:14] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[33mWARNING[0m:  [09-04-2024 00:43:25] Python-dotenv could not parse statement starting at line 9
[33mWARNING[0m:  [09-04-2024 00:43:25] Python-dotenv could not parse statement starting at line 12
[33mWARNING[0m:  [09-04-2024 00:43:25] Python-dotenv could not parse statement starting at line 15
[33mWARNING[0m:  [09-04-2024 00:43:25] Python-dotenv could not parse statement starting at line 16
[33mWARNING[0m:  [09-04-2024 00:43:25] Python-dotenv could not parse statement starting at line 18
[33mWARNING[0m:  [09-04-2024 00:43:25] Python-dotenv could not parse statement starting at line 19
[33mWARNING[0m:  [09-04-2024 00:43:25] Python-dotenv could not parse statement starting at line 21
[33mWARNING[0m:  [09-04-2024 00:43:25] Python-dotenv could not parse statement starting at line 22
[32mINFO[0m:     [09-04-2024 00:43:25] Set chroma_server_nofile to 65535
[32mINFO[0m:     [09-04-2024 00:43:25] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [09-04-2024 00:43:25] Starting component System
[36mDEBUG[0m:    [09-04-2024 00:43:25] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [09-04-2024 00:43:25] Starting component SimpleAssignmentPolicy
[36mDEBUG[0m:    [09-04-2024 00:43:25] Starting component SqliteDB
[36mDEBUG[0m:    [09-04-2024 00:43:25] Starting component QuotaEnforcer
[36mDEBUG[0m:    [09-04-2024 00:43:25] Starting component Posthog
[36mDEBUG[0m:    [09-04-2024 00:43:25] Starting component LocalSegmentManager
[36mDEBUG[0m:    [09-04-2024 00:43:25] Starting component SegmentAPI
[32mINFO[0m:     [09-04-2024 00:43:25] Started server process [[36m93525[0m]
[32mINFO[0m:     [09-04-2024 00:43:25] Waiting for application startup.
[32mINFO[0m:     [09-04-2024 00:43:25] Application startup complete.
[32mINFO[0m:     [09-04-2024 00:43:25] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [09-04-2024 01:26:21] 127.0.0.1:61222 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[36mDEBUG[0m:    [09-04-2024 01:26:22] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [09-04-2024 01:26:22] 127.0.0.1:61222 - "POST /api/v1/collections/4539bb59-6db1-42d9-b45d-81ad2ce6a936/add HTTP/1.1" 201
[32mINFO[0m:     [09-04-2024 01:26:22] 127.0.0.1:61222 - "POST /api/v1/collections/4539bb59-6db1-42d9-b45d-81ad2ce6a936/query HTTP/1.1" 200
[31mERROR[0m:    [09-04-2024 01:27:38] Collection chat-history already exists
Traceback (most recent call last):
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 81, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 76, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 101, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 82, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 96, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/chromadb/auth/fastapi.py", line 241, in wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 415, in create_collection
    return self._api.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/chromadb/api/segment.py", line 167, in create_collection
    coll, created = self._sysdb.create_collection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jasonsuarez/miniconda3/lib/python3.11/site-packages/chromadb/db/mixins/sysdb.py", line 225, in create_collection
    raise UniqueConstraintError(f"Collection {name} already exists")
chromadb.db.base.UniqueConstraintError: Collection chat-history already exists
[32mINFO[0m:     [09-04-2024 01:27:38] 127.0.0.1:61247 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [09-04-2024 01:28:56] 127.0.0.1:61270 - "GET /api/v1/collections/chat-history?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [09-04-2024 01:30:33] 127.0.0.1:61295 - "GET /api/v1/collections/chat-history?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [09-04-2024 01:30:34] 127.0.0.1:61295 - "POST /api/v1/collections/4539bb59-6db1-42d9-b45d-81ad2ce6a936/query HTTP/1.1" 200
[33mWARNING[0m:  [11-04-2024 10:36:28] Python-dotenv could not parse statement starting at line 9
[33mWARNING[0m:  [11-04-2024 10:36:28] Python-dotenv could not parse statement starting at line 12
[33mWARNING[0m:  [11-04-2024 10:36:28] Python-dotenv could not parse statement starting at line 15
[33mWARNING[0m:  [11-04-2024 10:36:28] Python-dotenv could not parse statement starting at line 16
[33mWARNING[0m:  [11-04-2024 10:36:28] Python-dotenv could not parse statement starting at line 18
[33mWARNING[0m:  [11-04-2024 10:36:28] Python-dotenv could not parse statement starting at line 19
[33mWARNING[0m:  [11-04-2024 10:36:28] Python-dotenv could not parse statement starting at line 21
[33mWARNING[0m:  [11-04-2024 10:36:28] Python-dotenv could not parse statement starting at line 22
[33mWARNING[0m:  [11-04-2024 10:36:28] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
[32mINFO[0m:     [11-04-2024 10:36:28] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [11-04-2024 10:36:28] Starting component System
[36mDEBUG[0m:    [11-04-2024 10:36:28] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [11-04-2024 10:36:28] Starting component SimpleAssignmentPolicy
[36mDEBUG[0m:    [11-04-2024 10:36:28] Starting component SqliteDB
[36mDEBUG[0m:    [11-04-2024 10:36:28] Starting component QuotaEnforcer
[36mDEBUG[0m:    [11-04-2024 10:36:28] Starting component Posthog
[36mDEBUG[0m:    [11-04-2024 10:36:28] Starting component LocalSegmentManager
[36mDEBUG[0m:    [11-04-2024 10:36:28] Starting component SegmentAPI
[32mINFO[0m:     [11-04-2024 10:36:28] Started server process [[36m38771[0m]
[32mINFO[0m:     [11-04-2024 10:36:28] Waiting for application startup.
[32mINFO[0m:     [11-04-2024 10:36:28] Application startup complete.
[32mINFO[0m:     [11-04-2024 10:36:28] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
